A1/semana17/s17/app1/models.py
from django.db import models

class Estudiantes(models.Model):
    nombre = models.CharField(max_length=100)
    carnet = models.CharField(max_length=10)
    edad = models.IntegerField()
    curso = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre

class Materias(models.Model):
    nombre = models.CharField(max_length=100)
    estds = models.ManyToManyField(Estudiantes
                                   ,related_name='materias')
    def __str__(self):
        return f"Materia: {self.nombre}"

A1/semana17/s17/app1/views.py
from django.shortcuts import render,redirect
from . import models
from .formularios import formaddest

def index(request):
    est = models.Estudiantes.objects.all() 
    mat = models.Materias.objects.all()
    return render(request,'index.html',
                  {'est':est,'mat':mat})
    
def formest(request):
    if request.method == 'POST':
        form = formaddest.FormEst(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = formaddest.FormEst()
    return render(request, 'formulario.html', {'form': form})

def gestud(request):
    #INSERT INTO Table VALUES ? ? ? ?
    models.Estudiantes.objects.create(
        nombre = request.POST.get('nom'), 
        carnet = request.POST.get('car'),
        edad = request.POST.get('ed'),
        curso = request.POST.get('cur')
        )
    return redirect('/')

def agrmat(request):
    form2 = formaddest.FormMaterias()
    return render(request,'formulario.html',
                  {'form':form2})

def editest(request,id):
    estudiante=models.Estudiantes.objects.get(id=id)
    form = formaddest.FormEst()
    return render(request,'formulario.html',
                  {'form':form,'est':estudiante})
    

def borrest(request,id):
    estudiante=models.Estudiantes.objects.get(id=id)
    estudiante.delete()
    return redirect('/')

A1/semana17/s17/app1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block titulo%}{%endblock%}</title>
</head>
<body>
    {%block contenido%}
    {%endblock%}
</body>
</html>

A1/semana17/s17/app1/templates/formaddmat.html
{% extends 'base.html' %}
{% block titulo %} Formulario {% endblock %}
{% block contenido %}
    <form action="/add/" method="post">
        {% csrf_token %}
        <label for="id_nombre">Nombre de la materia</label>
        {{ form.nombre }}
        <label for="id_estds">Selecciona los estudiantes:</label>
        {{ form.estds }}  
        <button type="submit">Click</button>
    </form>
{% endblock %}

A1/semana17/s17/app1/templates/formulario.html
{% extends 'base.html' %}
{% block titulo %} Formulario {% endblock %}
{% block contenido %}
    <form action="/add/" method="post">
        {% csrf_token %}
        <label for="id_nombre">Nombre</label>
        {{ form.nom }}
        
        <label for="id_carnet">Carnet</label>
        {{ form.car }}
        
        <label for="id_edad">Edad</label>
        {{ form.ed }}
        
        <label for="id_curso">Curso</label>
        {{ form.cur }}
        
        <button type="submit">Click</button>
    </form>
{% endblock %}

A1/semana17/s17/app1/templates/index.html
{%extends 'base.html'%}
{%block titulo%} Index {%endblock%}
{%block contenido%}

    <h1>Lista de materias</h1>
    <a href="/add2/"><button type="button" class="btn btn-primary">
        Ingresar nueva materia
    </button></a>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Estudiantes</th>
            </tr>
        </thead>
        <tbody>
            {%for m in mat%}
            <tr>
                <td>{{m.nombre}}</td>
                <td>{% for estudiante in m.estds.all %}
                    {{ estudiante.nombre }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

    <h1>Lista de estudiantes</h1>
    <a href="/formest/"><button type="button" class="btn btn-primary">
        Ingresar nuevo estudiante
    </button></a>
    <table class="table table-primary">
        <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Carnet</th>
                <th>Edad</th>
                <th>Curso</th>
                <th>Acciones</th>
                
            </tr>
        </thead>
        <tbody>
            {%for e in est%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{e.nombre}}</td>
                <td>{{e.carnet}}</td>
                <td>{{e.edad}}</td>
                <td>{{e.curso}}</td>
                <td>
                    <a href="/editar/{{e.id}}"><button type="button" class="btn btn-warning">Editar</button></a>
                    <a href="/borrar/{{e.id}}"><button type="button" class="btn btn-danger">Borrar</button></a>
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

{%endblock%}